export const owner = [
  {
    id: 1,
    name: "Masriono",
    img: "img/owner/masriono.jpg",
  },
  {
    id: 2,
    name: "Nur Lestari",
    img: "img/owner/nur lestari.jpg",
  },
];

export const staff = [
  {
    id: 1,
    name: "Murdianto ⚖️",
    img: "img/staff/murdianto.webp",
    position: "Karyawan",
    desc: "Penjaga pasar sayur dan provisi stok timbangan",
  },
  {
    id: 2,
    name: "Susanto 📒",
    img: "img/staff/susanto.webp",
    position: "Karyawan",
    desc: "Maintenans toko pasar dan stok bahan",
  },
  {
    id: 3,
    name: "Rohaila 💵",
    img: "img/staff/rohaila.webp",
    position: "Karyawan",
    desc: "Pengelola pengadaan barang dan laba rugi",
  },
  {
    id: 4,
    name: "Linawati 💵",
    img: "img/staff/linawati.webp",
    position: "Karyawan",
    desc: "Pengelola pengadaan barang dan laba rugi",
  },
  {
    id: 5,
    name: "Dimas Ramadan 👷‍♂️",
    img: "img/staff/dimas ramadan.webp",
    position: "Karyawan",
    desc: "Tulang punggung barang gudang",
  },
  {
    id: 6,
    name: "Andika 👷‍♂️",
    img: "img/staff/andika.webp",
    position: "Karyawan",
    desc: "Tulang punggung barang gudang",
  },
  {
    id: 7,
    name: "Jefri Ali Fernando 👷‍♂️",
    img: "img/staff/dimas ramadan.webp",
    position: "Karyawan",
    desc: "Tulang punggung barang gudang",
  },
  {
    id: 8,
    name: "Dwi Cahyani 🧺",
    img: "img/staff/dwi cahyani.webp",
    position: "Karyawan",
    desc: "Mitigasi rak dan pengalola transaksi",
  },
  {
    id: 9,
    name: "Arina Khusnawati Iswtiqomah 🧺",
    img: "img/staff/arina khusnawati istiqomah.webp",
    position: "Karyawan",
    desc: "Mitigasi rak dan pengalola transaksi",
  },
  {
    id: 10,
    name: "Made Wiratni 🧺",
    img: "img/staff/made wiratni.webp",
    position: "Karyawan",
    desc: "Mitigasi rak dan pengalola transaksi",
  },
  {
    id: 11,
    name: "Suci Permata Sari 🧺",
    img: "img/staff/suci permata sari.webp",
    position: "Karyawan",
    desc: "Mitigasi rak dan pengalola transaksi",
  },
  {
    id: 12,
    name: "Rika 🥬",
    img: "img/staff/rika.webp",
    position: "Karyawan",
    desc: "Semua yang berurusan dengan sayuran dan kulkas",
  },
  {
    id: 13,
    name: "Salsabela 🧺",
    img: "img/staff/salsabela.webp",
    position: "Karyawan",
    desc: "Mitigasi rak dan pengalola transaksi",
  },
];

export const activities = [
  {
    id: 1,
    title: "Syukuran",
    date: "Februari 2023",
    location: "Toko Nuri Jaya",
    desc: "Iki syukuran opo yo. Lupa saya...",
    img: "img/activities/1-syukuran.webp",
  },
  {
    id: 2,
    title: "Pantai Mutun",
    date: "Mei 2023",
    location: "Pantai Mutun",
    desc: "Ini adalah jalan-jalan pertama kami, setelah Toko Nuri Jaya dibuka. Di sini banyak sekali permainan yang kami lakukan.",
    img: "img/activities/2-pantai mutun.webp",
  },
  {
    id: 3,
    title: "Galungan",
    date: "Februari 2024",
    location: "Rumah Mbak Ela",
    desc: "Kami main ke tempat Mbak Ela yang sedang melaksanakan Hari Raya Galungan.",
    img: "img/activities/3-galungan.webp",
  },
  {
    id: 4,
    title: "Pantai Marina",
    date: "Maret 2026",
    location: "Pantai Marina",
    desc: "Di tahun kedua berdirinya Toko. Kami pergi jalan-jalan ke Pantai Marinsa.",
    img: "img/activities/4-pantai marina.webp",
  },
  {
    id: 5,
    title: "Permainan",
    date: "Maret 2026",
    location: "Toko Nuri Jaya",
    desc: "Disela-sela kesibukan kami di Toko. Ketua malah bagi-bagi hadiah.",
    img: "img/activities/5-permainan.webp",
  },
  {
    id: 6,
    title: "Mancing",
    date: "Maret 2026",
    location: "Gazebo Spontan",
    desc: "Tiba-tiba ngajal mancing. Gas lah...",
    img: "img/activities/6-mancing.webp",
  },
  {
    id: 7,
    title: "Makan-Makan",
    date: "Maret 2026",
    location: "Rumah Mbak Lina & Bang T",
    desc: "Sepertinya acara makan-makan kami belum selesai. Lanjut...",
    img: "img/activities/7-makan.webp",
  },
  {
    id: 8,
    title: "Isah-isah",
    date: "Maret 2026",
    location: "Rumah Mbak Lina & Bang-T",
    desc: "Heh... Ahkirnya beres-beres juga.",
    img: "img/activities/8-cuci piring.webp",
  },
];
